Repository ARMmbed/mbed-os-example-pelion, pull requests merged in 2019-12, with the labels that each got.

#66 Add target C030_R412M
  README.md
  bootloader/mbed-bootloader-ublox_c030_r412m-block_device-kvstore-v4.0.3.bin
  mbed_app.json
Labels: build-only, ready-to-merge

#68 Add support for EP_AGORA
  README.md
  bootloader/mbed-bootloader-ep_agora-block_device-kvstore-v4.0.2.hex
  mbed_app.json
Labels: build-only

#70 Add cy8cproto 062 4343w
  README.md
  bootloader/mbed-bootloader-cy8cproto-062-4343w-internal-flash-kvstore-v4.0.1.hex
  mbed_app.json
Labels: build-only, ready-to-merge

#79 Remove invisible unicode char from mbed_app.json
  mbed_app.json
Labels: Requires CI

#80 Revert "Add cy8cproto 062 4343w"
  README.md
  bootloader/mbed-bootloader-cy8cproto-062-4343w-internal-flash-kvstore-v4.0.1.hex
  mbed_app.json
Labels: ready-to-merge

#73 README.md: Adds instructions how to obtain bootloader-details
  README.md
Labels: ready-to-merge
