Repository ARMmbed/mbed-os-example-pelion, pull requests merged in 2020-01, with the labels that each got.

#82 Make get_res writable
  main.cpp
Labels: Requires CI

#71 Add bl + config for Nucleo H743ZI2.
  README.md
  bootloader/mbed-bootloader-nucleo-h743zi2-internal-flash-no-rot-4.1.1.bin
  mbed_app.json
Labels: Requires CI, build-only

#72 Add bl + config for Nucleo L4R5ZI with ESP8266.
  README.md
  bootloader/mbed-bootloader-nucleo_l4r5zi-internal_flash_no_rot-ca089bb.bin
  mbed_app.json
Labels: build-only

#84 Support NUMAKER_IOT_M487 V1.3 (re-raise)
  README.md
  bootloader/mbed-bootloader-m487_iot-block_device-kvstore-v4.1.0.bin
  drivers/storage/COMPONENT_NUSD.lib
  mbed_app.json
Labels: build-only, ready-to-merge

#89 Deprecated API updates
  drivers/COMPONENT_WIFI_ISM43362.lib
  main.cpp
Labels: Requires CI, ready-to-merge

#85 Add factory reset
  main.cpp
Labels: Requires CI

#69 Add Seeed Arch-MAX support
  README.md
  bootloader/mbed-bootloader-arch_max-block_device-kvstore-v4.0.3.bin
  mbed_app.json
Labels: Requires CI

#96 Add Renesas GR-PEACH and GR-LYCHEE support
  README.md
  bootloader/mbed-bootloader-gr_lychee-internal_flash-no_rot-v4.1.2.bin
  bootloader/mbed-bootloader-gr_peach-internal_flash-no_rot-v4.1.2.bin
  mbed_app.json
Labels: Requires CI

#86 Add Seeed Wio 3G support
  README.md
  bootloader/mbed-bootloader-wio_3g-internal_flash-no_rot-v4.1.2.bin
  mbed_app.json
Labels: Requires CI

#87 Tweaks to fix FOTA for EP_AGORA
  bootloader/mbed-bootloader-ep_agora-block_device-kvstore-v4.0.2.hex
  bootloader/mbed-bootloader-ep_agora-external_kvstore-spif-v4.1.2.bin
  mbed_app.json
Labels: Requires CI

#88 Support NUMAKER_PFM_M487 (re-raise)
  README.md
  bootloader/mbed-bootloader-m487-block_device-kvstore-v4.1.0.bin
  mbed_app.json
Labels: Requires CI

#102 PR template additions
  .github/pull_request_template.md
Labels: documentation, ready-to-merge

#95 Update Pelion E2E test library to 0.2.1
  README.md
  TESTS/pelion-e2e-python-test-library.lib
  mbed_app.json
Labels: Requires CI

#105 Cleaning up unreachable links
  main.cpp
Labels: Requires CI

#90 Add flush of the STDIN buffer and reset EP_AGORA baud to default
  main.cpp
  mbed_app.json
Labels: Requires CI
